### ISSUE TITLE
Konsave: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by rabin-io** [Prayag2/konsave#47]
**Describe the bug**

On Fedora 35 with Python 3.10 I get this message on save

```
❯ konsave --force --save Default
Konsave: Saving profile...
Konsave: list indices must be integers or slices, not str
Please check the log at /home/rabin/konsave_log.txt for more details.
Konsave: 'NoneType' object is not subscriptable
Please check the log at /home/rabin/konsave_log.txt for more details.
```

**To reproduce**

**Expected behavior**

Not to fail, and a better error handling.

**Screenshots**

**System information**
 - Fedora 35
 - pip install --user
 - 2.1.1

**Additional context**

```
File: /home/user/konsave_log.txt
[02/11/2021 10:22:58]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/konsave/funcs.py", line 40, in inner_func
    function = func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/konsave/funcs.py", line 127, in read_konsave_config
    parse_keywords(tokens, TOKEN_SYMBOL, konsave_config)
  File "/home/user/.local/lib/python3.10/site-packages/konsave/parse.py", line 54, in parse_keywords
    location = parsed[item][name]["location"]
TypeError: list indices must be integers or slices, not str

[02/11/2021 10:22:58]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/konsave/funcs.py", line 40, in inner_func
    function = func(*args, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/konsave/funcs.py", line 170, in save_profile
    konsave_config = read_konsave_config(CONFIG_FILE)["save"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Prayag2** [comment]
I'm so sorry I'm really late. Please paste the contents of the config file (`~/.config/konsave/conf.yaml`) here.

**Comment by rabin-io** [comment]
```
---
entries:
    - gtk-2.0
    - gtk-3.0
    - gtk-4.0
    - Kvantum
    - latte
    - dolphinrc
    - konsolerc
    - kcminputrc
    - kdeglobals
    - kglobalshortcutsrc
    - klipperrc
    - krunnerrc
    - kscreenlockerrc
    - ksmserverrc
    - kwinrc
    - kwinrulesrc 
    - plasma-org.kde.plasma.desktop-appletsrc
    - plasmarc
    - plasmashellrc
    - gtkrc
    - gtkrc-2.0 
    - lattedockrc 
    - breezerc 
    - oxygenrc
    - lightlyrc 
    - ksplashrc
```

**Comment by Prayag2** [comment]
This is a really old version of the config file. Just delete it and run konsave again and it should work just fine!
