### ISSUE TITLE
`The 'Konsave==2.0.2' distribution was not found and is required by the application`

### ISSUE THREAD

**Issue by mmahmoudian** [Prayag2/konsave#82]
## Describe the bug
Upon running konsave (with or without any argument) I will get an error regarding konsave version 2.0.2 where as I'm on the latest (2.2.0):

```console
❯  konsave
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 629, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 966, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 873, in _resolve_dist
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (Konsave 2.2.0 (/usr/lib/python3.10/site-packages), Requirement.parse('Konsave==2.0.2'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mehrad/.local/bin/konsave", line 33, in <module>
    sys.exit(load_entry_point('Konsave==2.0.2', 'console_scripts', 'konsave')())
  File "/home/mehrad/.local/bin/konsave", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/konsave/__init__.py", line 3, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3324, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3298, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3336, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 631, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 644, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 827, in resolve
    dist = self._resolve_dist(
  File "/usr/lib/python3.10/site-packages/pkg_resources/__init__.py", line 868, in _resolve_dist
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Konsave==2.0.2' distribution was not found and is required by the application
```

## To reproduce
Run `konsave` or `konsave --version` or `konsave --wipe` or `konsave --list` or etc.

I tried uninstalling and re-installing. Same situation. I also tried removing (well, renaming) the `~/.config/konsave/` and see if that has any effect. But still I get the same exact error.

## Expected behavior
Not getting error

## Screenshots
--not applicable imho--

## System information
 - **OS or Linux distribution:** Manjaro (fully updated)
 - **How did you install Konsave?** From AUR
 - **What version of Konsave are you using? Did you try updating?** `2.2.0-1 AUR`

```console
❯  python --version
Python 3.10.10
```

## Additional context
--not applicable--

**Comment by Prayag2** [comment]
The AUR package works for me. Please mention this issue on the AUR page itself as the AUR package is not maintained by me.
