### ISSUE TITLE
Cannot execute konsave

### ISSUE THREAD

**Issue by nirav-mj** [Prayag2/konsave#99]
**Describe the bug**
Hi,

First of all I'm new to linux, with that being said I installed konsave from repo
using the following cmd
**_sudo pacman -S konsave                                                                                                                      
resolving dependencies...
looking for conflicting packages...

Packages (2) python-pyaml-23.7.0-1  konsave-2.2.0-2

Total Download Size:   0.06 MiB
Total Installed Size:  0.23 MiB_**

**To reproduce**

**_Traceback (most recent call last):
  File "/usr/bin/konsave", line 33, in <module>
    sys.exit(load_entry_point('Konsave==2.2.0', 'console_scripts', 'konsave')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/konsave", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/konsave/__init__.py", line 3, in <module>
    from pkg_resources import get_distribution, DistributionNotFound
ModuleNotFoundError: No module named 'pkg_resources'_**

**System information**
 - OS or Linux distribution: [ArchLinux Manjaro KDE]
 - How did you install Konsave? [Package manager]
 - What version of Konsave are you using? Did you try updating? 2.2.0-2

**Additional context**

**Comment by nirav-mj** [comment]
Forgot to add, after install I entered konsave -h and received an error mentioned in the issue.

**Comment by nirav-mj** [comment]
Sorry couldn't wait, figured it out. It was missing PIP and setuptools, it's all good now.

Where does konsave saves the profile and can I change the path?

**Comment by Prayag2** [comment]
> Where does konsave saves the profile and can I change the path?

No, you can't change the path at the moment. It saves the profiles in `~/.config/konsave/profiles`.
